config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :message do
    resources :comments
  end
  root 'message#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    has_many :comments
    validates :title,presence: true,length: {minimum: 30}
    validates :desc,presence: true,length: {minimum: 20}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :find_message, only: [:create,:update,:edit,:destroy]
    before_action :find_comment, only: [:edit,:update,:destroy]
    def create
        @message=Message.find(params[:message_id])
        @comment=@message.comments.create(comment_parmas)
        @comment.user_id=current_user.id

        if @comment.save
            redirect_to message_path(@message)
        else
            render :new, status: :unprocessable_entity
        end
    end
    def edit
    end
    def update
        if @comment.update(comment_parmas)
            redirect_to message_path(@message)
        else
            render :edit,status: :unprocessable_entity
        end
    end
    def destroy
        @comment.destroy
        redirect_to message_path(@message)
    end
    private
    def comment_parmas
        params.require(:comment).permit(:content)
    end
    def find_message
        @message=Message.find(params[:message_id])
    end
    def find_comment
        @comment=@message.comments.find(params[:id])

    end
end

app/controllers/message_controller.rb
class MessageController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]

    def index
        @messages=Message.all.order("created_at DESC")
    end
    def show
        @message=Message.find(params[:id])
        rescue ActiveRecord::RecordNotFound
        flash[:error]="This message does not exist."
        redirect_to  messages_path
    end
    def new
        @message=current_user.messages.build
    end
    def create
        @message=current_user.messages.build(message_params)
        if @message.save
            flash[:notice]='Message Post Successfully'
            redirect_to message_index_path
        else
            render :new, status: :unprocessable_entity
        end
    end
    def edit
        @message=Message.find(params[:id])
        rescue ActiveRecord::RecordNotFound
            flash[:error]="With given Id Message not found"
            redirect_to message_index_path
        end
    def update
        @message=Message.find(params[:id])
        if @message.update(message_params)
            flash[:notice]= "Post has been updated successfully!"
            redirect_to message_index_path
        else
            render :edit, status: :unprocessable_entity
        end
    end
    def destroy
        @message=Message.find(params[:id])
        @message.delete
        flash[:notice]="Message Deleted Successfully"
        rescue ActiveRecord::RecordNotFound
            redirect_to  message_index_path
        end
    private
    def message_params
        params.require(:message).permit(:title,:desc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/views/comments/_comment.html.erb
<div class="card mb-2">
  <div class="card-body">
    <h4><%= comment.content%></h4><p class="float-end">By- <%=comment.user_id %></p>
    <p>Comment at <%= time_ago_in_words(comment.created_at) %></p>
    <% if user_signed_in? %>
    <% if current_user.id == comment.user_id%>
        <%= link_to 'Edit', edit_message_comment_path(comment.message, comment),class:"btn btn-info"%>
        <%= link_to 'Delete', message_comment_path(comment.message, comment),data: {turbo_method: 'delete', turbo_confirm: "Are you sure"},class:"btn btn-outline-danger"%>
    <% end %>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@message,@message.comments.build] ) do |f| %>
<div class="mb-3">
    <%= f.label :"comment :",class:"form-label"%>
    <%= f.text_field :content,class:"form-control",require: true%>
  </div>
<%= f.submit "comment",class:"btn btn-primary"%>
<% end %>

app/views/comments/edit.html.erb
<%= simple_form_for([@message,@comment],html: {class: "mt-5"}) do |f| %>
<div class="mb-3">
    <%= f.label :"comment :",class:"form-label"%>
    <%= f.text_field :content,class:"form-control",require: true%>
  </div>
<%= f.submit "Edit comment",class:"btn btn-primary"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Espn</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>

  <body>
       <header>
      <nav class="navbar navbar-expand-lg p-4" style="background-color: #00BDAA;">
      <div class="container-fluid">
        <%= link_to 'ESPN FAN FORUM',root_path,class:"navbar-brand fs-2 mx-5"%>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        
        <% if user_signed_in? %>
          <li class="nav-item ">
          <%= link_to 'Post Message',new_message_path,class:"nav-link active fs-4" %>
        </li>
        <% end %>
         </ul>
        <ul class="navbar-nav ms-auto">
        <% if current_user.present? %>
        <li class="nav-item ms-auto">
          <%= link_to 'Sign Out',destroy_user_session_path,data: {turbo_method: 'delete', turbo_confirm: "Are you sure"},class:"nav-link active fs-4 mx-3 ms-auto"%>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to 'Login',new_user_session_path,class:"nav-link active fs-4 mx-3" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Signup',new_user_registration_path,class:"nav-link active fs-4 mx-3" %>
        </li>
        <% end %>
        </ul>
        </div>
      </div>
    </nav>
    </header>
    <div class="container">
    <% flash.each do |type,msg| %>
      <div class="alert alert-<%= type=="notice" ? "success" : "danger"%> alert-dismissible fade show" role="alert">
      <strong><%= msg %></strong>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div style="position:relative">
    <% end %>
    <%= yield %>
    </div>
    <footer style="background-color: #00BDAA;" class="fixed-bottom p-3">
      <span>
      <a href="#"><%= link_to 'ESPN.com',root_path%></a> &nbsp | &nbsp;<span class="far fa-copyright">&nbsp;&nbsp;</span>2024 All Rights Reserved.</span>
    </footer>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script>
    $('document').ready(function(){ 
      $('.alert').fadeOut(5000);
      $('.btn-close').click(function(){
        $('.alert').slideUp();
      })
     })
  </script>
</html>

app/views/message/edit.html.erb
<h2 class="text-center">Add New Message</h2>
<%= simple_form_for(@message,html: {class: "mt-5"}) do |form| %>
<div class="row mb-3">
    <%= form.label :"Title :",class:"col-sm-2 col-form-label"%>
    <div class="col-sm-10">
      <%= form.text_field :title,class:"form-control",placeholder:"Enter Message title :",required: true%>
      <% if @message.errors.any? %>
        <% @message.errors.full_messages_for(:title).each do |msg| %>
            <p style="color:red;font-size:1rem"><%= msg %></p>
        <% end %>
        <% end %>
    </div>
</div>
<div class="row mb-3">
    <%= form.label :"Description :",class:"col-sm-2 col-form-label"%>
    <div class="col-sm-10">
      <%= form.text_area :desc,class:"form-control",placeholder:"Enter Message :",required: true,rows: 10,cols: 10%>
      <% if @message.errors.any? %>
        <% @message.errors.full_messages_for(:desc).each do |msg| %>
            <p style="color:red;font-size:1rem"><%= msg %></p>
        <% end %>
        <% end %>
    </div>
</div>
<div class="d-grid gap-2 col-6 mx-auto">
<%= form.submit "Fix Message",class:"btn btn-info"%>
<%= link_to 'Back', message_path, class: "btn btn-secondary" %>
</div>
<% end %>

app/views/message/index.html.erb
<% @messages.each do |msg| %>
<div class="col-md-10 col-md-offset-2 mx-auto mb-4 mt-4">
<div class="card">
  <div class="card-body">
    <h2 class="card-title"><%= msg.title %></h2>
    <%= link_to 'Join Discussion',message_path(msg),class:"btn btn-dark float-end mt-4"%>
  </div>
</div>
</div>
<% end %>
<div class="col-md-10 col-md-offset-2 mx-auto mb-4 mt-4">
<%= link_to 'Create Message',new_message_path,class:"btn btn-primary text-white btn-lg"%>
</div>

app/views/message/new.html.erb
<h2 class="text-center">Post Message</h2>
<%= form_with scope: :message, :url =>{:action=>'create'},html: {class: "mt-5"} do |form| %>
<div class="row mb-3">
    <%= form.label :"Title :",class:"col-sm-2 col-form-label"%>
    <div class="col-sm-10">
      <%= form.text_field :title,class:"form-control",placeholder:"Enter Message title :",required: true%>
      <% if @message.errors.any? %>
        <% @message.errors.full_messages_for(:title).each do |msg| %>
            <p style="color:red;font-size:1rem"><%= msg %></p>
        <% end %>
        <% end %>
    </div>
</div>
<div class="row mb-3">
    <%= form.label :"Description :",class:"col-sm-2 col-form-label"%>
    <div class="col-sm-10">
      <%= form.text_area :desc,class:"form-control",placeholder:"Enter Message :",required: true,rows: 10,cols: 10%>
      <% if @message.errors.any? %>
        <% @message.errors.full_messages_for(:desc).each do |msg| %>
            <p style="color:red;font-size:1rem"><%= msg %></p>
        <% end %>
        <% end %>
    </div>
</div>
<div class="d-grid gap-2 col-6 mx-auto">
<%= form.submit "Create Message",class:"btn btn-info"%>
</div>
<% end %>

app/views/message/show.html.erb
<div class="card">
  <h5 class="card-header">Featured</h5>
  <div class="card-body">
    <h2 class="card-title"><%= @message.title %></h2>
    <p class="card-text">Posted<%=time_ago_in_words(@message.created_at)%> ago</p>
    <p class="card-text fs-5"><%= @message.desc %></p>
    <p class="d-inline-flex gap-1">
      <% if user_signed_in?  %>
      <% if current_user.id == @message.user_id%>
      <%= link_to 'Edit', edit_message_path(@message), class: "btn btn-secondary" %>
      <%= link_to 'Delete',@message,data: {turbo_method: 'delete', turbo_confirm: "Are you sure"},class:"btn btn-danger"%>
      <% end%>
      <% end%>
  <% if @message.comments.present? %>
      <h3>Comments :</h3>
      <%= render @message.comments %>
  <% end %>
  <h3>Join Discussion</h3>
  <%= render 'comments/form' %> 
</div>
</div>
<%= link_to 'Back',root_path,class:"btn btn-secondary btn-lg mt-3"%>